import random

def make_nick(ftext):
    result = []

    item = [' •🌱💚﴿ֆ ❥', '🍿﴿ֆ ❥', '• 🌸💸 ❥˓  ', '💝🎀﴿ֆ', ' • 🐼🌿﴾ֆ', ' •🙊💙﴿ֆ ❥', '-🐥✨﴿ֆ ❥ ', '•|• 〄💖‘',
    ' ⚡️💊 •|•℡', '- ⁽🌷✨₎ֆ', '❥┇👑🔥“', '💜💭℡ֆ', '-┆💙👒♕', '- ⁽🎩🍿₎ֆ',
    '“̯ 🐼💗 |℡', '⁞ 🐝🍷', '┋⁽❥̚͢₎ 🐣💗', '•|• ✨🌸‘', '  ֆ 💭💔ۦ', 'ֆ 💛💭ۦ', 'ֆ ⚡️🔱ۦ',
    '℡ᴖ̈💜✨⋮', '⋮⁽🌔☄️₎ۦ˛', '⁞❉💥┋♩', ' ⁞✦⁽☻🔥₎“ٰۦ', '℡ ̇₎ ✨🐯⇣✦', '⁞♩⁽💎🌩₎⇣✿',
    'ۦٰ‏┋❥ ͢˓🦁💛ۦ‏', '⚡️♛ֆ₎', '♛⇣🐰☄️₎✦', '⁾⇣✿💖┊❥', ' ₎✿💥🎃 ⁞“❥', '😴🌸✿⇣', '❥┊⁽ ℡🦁🌸']



    text = ftext.replace('a', 'α')
    text = text.replace('b', 'в')
    text = text.replace('c', '¢')
    text = text.replace('d', '∂')
    text = text.replace('e', 'є')
    text = text.replace('f', 'ƒ')
    text = text.replace('g', 'g')
    text = text.replace('h', 'н')
    text = text.replace('i', 'ι')
    text = text.replace('j', 'נ')
    text = text.replace('k', 'к')
    text = text.replace('l', 'ℓ')
    text = text.replace('m', 'м')
    text = text.replace('n', 'η')
    text = text.replace('o', 'σ')
    text = text.replace('p', 'ρ')
    text = text.replace('q', 'q')
    text = text.replace('r', 'я')
    text = text.replace('s', 'ѕ')
    text = text.replace('t', 'т')
    text = text.replace('u', 'υ')
    text = text.replace('v', 'ν')
    text = text.replace('w', 'ω')
    text = text.replace('x', 'χ')
    text = text.replace('y', 'у')
    text = text.replace('z', 'z')

    result.append(f"{text} {random.choice(item)}")

    #-----------------(#UzbProMax-2)--------------------#
    text = ftext
    text = text.replace('a', 'Á')
    text = text.replace('b', 'ß')
    text = text.replace('c', 'Č')
    text = text.replace('d', 'Ď')
    text = text.replace('e', 'Ĕ')
    text = text.replace('f', 'Ŧ')
    text = text.replace('g', 'Ğ')
    text = text.replace('h', 'Ĥ')
    text = text.replace('i', 'Ĩ')
    text = text.replace('j', 'Ĵ')
    text = text.replace('k', 'Ķ')
    text = text.replace('l', 'Ĺ')
    text = text.replace('m', 'M')
    text = text.replace('n', 'Ń')
    text = text.replace('o', 'Ő')
    text = text.replace('p', 'P')
    text = text.replace('q', 'Q')
    text = text.replace('r', 'Ŕ')
    text = text.replace('s', 'Ś')
    text = text.replace('t', 'Ť')
    text = text.replace('u', 'Ú')
    text = text.replace('v', 'V')
    text = text.replace('w', 'Ŵ')
    text = text.replace('x', 'Ж')
    text = text.replace('y', 'Ŷ')
    text = text.replace('z', 'Ź')

    result.append(text +' '+ random.choice(item))

    #-----------------(#UzbProMax-3)--------------------#
    text = ftext
    text = text.replace('a', 'ค')
    text = text.replace('b', '๒')
    text = text.replace('c', 'ς')
    text = text.replace('d', '๔')
    text = text.replace('e', 'є')
    text = text.replace('f', 'Ŧ')
    text = text.replace('g', 'g')
    text = text.replace('h', 'ђ')
    text = text.replace('i', 'เ')
    text = text.replace('j', 'ן')
    text = text.replace('k', 'к')
    text = text.replace('l', 'l')
    text = text.replace('m', '๓')
    text = text.replace('n', 'ภ')
    text = text.replace('o', '๏')
    text = text.replace('p', 'ק')
    text = text.replace('q', 'ợ')
    text = text.replace('r', 'г')
    text = text.replace('s', 'ร')
    text = text.replace('t', 't')
    text = text.replace('u', 'ย')
    text = text.replace('v', 'ש')
    text = text.replace('w', 'ฬ')
    text = text.replace('x', 'א')
    text = text.replace('y', 'ץ')
    text = text.replace('z', 'z')

    result.append(text +' '+ random.choice(item))

    #-----------------(#UzbProMax-4)--------------------#
    text = ftext
    text = text.replace('a', 'ä')
    text = text.replace('b', 'b')
    text = text.replace('c', 'ċ')
    text = text.replace('d', 'd')
    text = text.replace('e', 'ë')
    text = text.replace('f', 'f')
    text = text.replace('g', 'ġ')
    text = text.replace('h', 'h')
    text = text.replace('i', 'ï')
    text = text.replace('j', 'j')
    text = text.replace('k', 'k')
    text = text.replace('l', 'l')
    text = text.replace('m', 'm')
    text = text.replace('n', 'n')
    text = text.replace('o', 'ö')
    text = text.replace('p', 'p')
    text = text.replace('q', 'q')
    text = text.replace('r', 'r')
    text = text.replace('s', 's')
    text = text.replace('t', 't')
    text = text.replace('u', 'ü')
    text = text.replace('v', 'v')
    text = text.replace('w', 'w')
    text = text.replace('x', 'x')
    text = text.replace('y', 'ÿ')
    text = text.replace('z', 'ż')

    result.append(text +' '+ random.choice(item))

    #-----------------(#UzbProMax-5)--------------------#
    text = ftext
    text = text.replace('a', 'ɑ̝̚')
    text = text.replace('b', 'в̝̚')
    text = text.replace('c', 'c̝̚')
    text = text.replace('d', 'd̝̚')
    text = text.replace('e', 'ǝ̝̚')
    text = text.replace('f', 'г̵̵')
    text = text.replace('g', 'G̝̚')
    text = text.replace('h', 'н̝̚')
    text = text.replace('i', 'ı̝̚')
    text = text.replace('j', 'τ')
    text = text.replace('k', 'к̝')
    text = text.replace('l', 'l̝̚')
    text = text.replace('m', 'м̝̚')
    text = text.replace('n', 'и̝̚')
    text = text.replace('o', 'σ̝̚')
    text = text.replace('p', 'ρ̝̚')
    text = text.replace('q', 'Q̝̚')
    text = text.replace('r', 'я̝̚')
    text = text.replace('s', 'ƨ̝̚')
    text = text.replace('t', 'т̝̚')
    text = text.replace('u', 'υ̝̚')
    text = text.replace('v', 'ν̝̚')
    text = text.replace('w', 'ω̝̚')
    text = text.replace('x', 'x̝̚')
    text = text.replace('y', 'ч̝̚')
    text = text.replace('z', 'z̝̚')

    result.append(text +' '+ random.choice(item))

    #-----------------(#UzbProMax-6)--------------------#
    text = ftext
    text = text.replace('a', 'ɑ̃̾')
    text = text.replace('b', 'в̃̾')
    text = text.replace('c', 'c̃̾')
    text = text.replace('d', 'd̃̾')
    text = text.replace('e', 'ǝ̃̾')
    text = text.replace('f', 'г̵̵')
    text = text.replace('g', 'G̃̾')
    text = text.replace('h', 'н̃̾')
    text = text.replace('i', 'ı̃̾')
    text = text.replace('j', 'τ̃̾')
    text = text.replace('k', 'к̃̾')
    text = text.replace('l', 'l̃̾')
    text = text.replace('m', 'м̃̾')
    text = text.replace('n', 'и̃̾')
    text = text.replace('o', 'σ̃̾')
    text = text.replace('p', 'ρ̃̾')
    text = text.replace('q', 'Q̃̾')
    text = text.replace('r', 'я̃̾')
    text = text.replace('s', 'ƨ̃̾')
    text = text.replace('t', 'т̃̾')
    text = text.replace('u', 'υ̃̾')
    text = text.replace('v', 'ν̃̾')
    text = text.replace('w', 'ω̃̾')
    text = text.replace('x', 'x̃̾')
    text = text.replace('y', 'ч̃̾')
    text = text.replace('z', 'z̃̾')

    result.append(text +' '+ random.choice(item))

    #-----------------(#UzbProMax-7)--------------------#
    text  = ftext
    text  = text.replace('a', '[̲̅a̲̅]')
    text  = text.replace('b', '[̲̅b̲̅]')
    text  = text.replace('c', '[̲̅c̲̅]')
    text  = text.replace('d', '[̲̅d̲̅]')
    text  = text.replace('e', '[̲̅e̲̅]')
    text  = text.replace('f', '[̲̅f̲̅]')
    text  = text.replace('g', '[̲̅g̲̅]')
    text  = text.replace('h', '[̲̅h̲̅]')
    text  = text.replace('i', '[̲̅i̲̅]')
    text  = text.replace('j', '[̲̅j̲̅]')
    text  = text.replace('k', '[̲̅k̲̅]')
    text  = text.replace('l', '[̲̅l̲̅]')
    text  = text.replace('m', '[̲̅m̲̅]')
    text  = text.replace('n', '[̲̅n̲̅]')
    text  = text.replace('o', '[̲̅o̲̅]')
    text  = text.replace('p', '[̲̅p̲̅]')
    text  = text.replace('q', '[̲̅q̲̅]')
    text  = text.replace('r', '[̲̅r̲̅]')
    text  = text.replace('s', '[̲̅s̲̅]')
    text  = text.replace('t', '[̲̅t̲̅]')
    text  = text.replace('u', '[̲̅u̲̅]')
    text  = text.replace('v', '[̲̅v̲̅]')
    text  = text.replace('w', '[̲̅w̲̅]')
    text  = text.replace('x', '[̲̅x̲̅]')
    text  = text.replace('y', '[̲̅y̲̅]')
    text    = text.replace('z', 'z')

    result.append(text +' '+ random.choice(item))

    #-----------------(#UzbProMax-8)--------------------#
    text = ftext
    text = text.replace('a', 'ɐ')
    text = text.replace('b', 'q')
    text = text.replace('c', 'ɔ')
    text = text.replace('d', 'p')
    text = text.replace('e', 'ǝ')
    text = text.replace('f', 'ɟ')
    text = text.replace('g', 'ƃ')
    text = text.replace('h', 'ɥ')
    text = text.replace('i', 'ı')
    text = text.replace('j', 'ſ')
    text = text.replace('k', 'ʞ')
    text = text.replace('l', 'ן')
    text = text.replace('m', 'ɯ')
    text = text.replace('n', 'u')
    text = text.replace('o', 'o')
    text = text.replace('p', 'd')
    text = text.replace('q', 'b')
    text = text.replace('r', 'ɹ')
    text = text.replace('s', 's')
    text = text.replace('t', 'ʇ')
    text = text.replace('u', 'n')
    text = text.replace('v', 'ʌ')
    text = text.replace('w', 'ʍ')
    text = text.replace('x', 'x')
    text = text.replace('y', 'ʎ')
    text = text.replace('z', 'z')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-9)--------------------#
    text = ftext
    text = text.replace('A', 'Ⓐ')
    text = text.replace('a', 'ⓐ')
    text = text.replace('b', 'ⓑ')
    text = text.replace('c', '©')
    text = text.replace('d', 'ⓓ')
    text = text.replace('e', 'ⓔ')
    text = text.replace('f', 'ⓕ')
    text = text.replace('g', 'ⓖ')
    text = text.replace('h', 'ⓗ')
    text = text.replace('i', 'ⓘ')
    text = text.replace('j', 'ⓙ')
    text = text.replace('k', 'ⓚ')
    text = text.replace('l', 'ⓛ')
    text = text.replace('M', 'ⓜ')
    text = text.replace('m', 'ⓜ')
    text = text.replace('n', 'ⓝ')
    text = text.replace('o', 'ⓞ')
    text = text.replace('p', 'ⓟ')
    text = text.replace('q', 'ⓠ')
    text = text.replace('r', 'ⓡ')
    text = text.replace('s', 'ⓢ')
    text = text.replace('t', 'ⓣ')
    text = text.replace('u', 'ⓤ')
    text = text.replace('v', 'ⓥ')
    text = text.replace('w', 'ⓦ')
    text = text.replace('x', 'ⓧ')
    text = text.replace('y', 'ⓨ')
    text = text.replace('z', 'ⓩ')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-10)--------------------#
    text = ftext
    text = text.replace('a', 'Ā')
    text = text.replace('b', '乃')
    text = text.replace('c', 'Ċ')
    text = text.replace('d', 'Ɖ')
    text = text.replace('e', 'Ē')
    text = text.replace('f', '₣')
    text = text.replace('g', 'Ǥ')
    text = text.replace('h', 'Ħ')
    text = text.replace('i', 'Ī')
    text = text.replace('j', 'J')
    text = text.replace('k', '₭')
    text = text.replace('l', 'Ŀ')
    text = text.replace('m', 'M')
    text = text.replace('n', '₦')
    text = text.replace('o', 'Ō')
    text = text.replace('p', 'P')
    text = text.replace('q', 'Ǭ')
    text = text.replace('r', 'Ṝ')
    text = text.replace('s', 'Ƨ')
    text = text.replace('t', 'Ŧ')
    text = text.replace('u', 'Ū')
    text = text.replace('v', '∀')
    text = text.replace('w', 'ฬ')
    text = text.replace('x', 'Ж')
    text = text.replace('y', 'Ȳ')
    text = text.replace('z', 'Ƶ')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-11)--------------------#
    text = ftext
    text = text.replace('a', 'ᾋ')
    text = text.replace('b', 'ϐ')
    text = text.replace('c', 'Ƈ')
    text = text.replace('d', 'Ɖ')
    text = text.replace('e', 'Ἕ')
    text = text.replace('f', 'Ғ')
    text = text.replace('g', 'Ɠ')
    text = text.replace('h', 'Ἤ')
    text = text.replace('i', 'Ἷ')
    text = text.replace('j', 'Ј')
    text = text.replace('k', 'Ḱ')
    text = text.replace('l', 'Ŀ')
    text = text.replace('m', 'Ṃ')
    text = text.replace('n', 'Ɲ')
    text = text.replace('o', 'Ὃ')
    text = text.replace('p', 'Ƥ')
    text = text.replace('q', 'Q')
    text = text.replace('r', 'Ȓ')
    text = text.replace('s', 'Ṩ')
    text = text.replace('t', 'Ҭ')
    text = text.replace('u', 'Ȗ')
    text = text.replace('v', 'V')
    text = text.replace('w', 'Ẃ')
    text = text.replace('x', 'Ẋ')
    text = text.replace('y', 'Ὓ')
    text = text.replace('z', 'Ẕ')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-12)--------------------#
    text = ftext
    text = text.replace('a', 'მ')
    text = text.replace('b', 'ჩ')
    text = text.replace('c', 'ƈ')
    text = text.replace('d', 'ძ')
    text = text.replace('e', 'ε')
    text = text.replace('f', 'բ')
    text = text.replace('g', 'ց')
    text = text.replace('h', 'հ')
    text = text.replace('i', 'ἶ')
    text = text.replace('j', 'ʝ')
    text = text.replace('k', 'ƙ')
    text = text.replace('l', 'l')
    text = text.replace('m', 'ო')
    text = text.replace('n', 'ղ')
    text = text.replace('o', 'օ')
    text = text.replace('p', 'ր')
    text = text.replace('q', 'գ')
    text = text.replace('r', 'ɾ')
    text = text.replace('s', 'ʂ')
    text = text.replace('t', 'է')
    text = text.replace('u', 'մ')
    text = text.replace('v', 'ν')
    text = text.replace('w', 'ω')
    text = text.replace('x', 'ჯ')
    text = text.replace('y', 'ყ')
    text = text.replace('z', 'z')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-13)--------------------#
    text = ftext
    text = text.replace('a', 'ᴬ')
    text = text.replace('b', 'ᴮ')
    text = text.replace('c', 'ᶜ')
    text = text.replace('d', 'ᴰ')
    text = text.replace('e', 'ᴱ')
    text = text.replace('f', 'ᶠ')
    text = text.replace('g', 'ᴳ')
    text = text.replace('h', 'ᴴ')
    text = text.replace('i', 'ᴵ')
    text = text.replace('j', 'ᴶ')
    text = text.replace('k', 'ᴷ')
    text = text.replace('l', 'ᴸ')
    text = text.replace('m', 'ᴹ')
    text = text.replace('n', 'ᴺ')
    text = text.replace('o', 'ᴼ')
    text = text.replace('p', 'ᴾ')
    text = text.replace('q', 'ᵠ')
    text = text.replace('r', 'ᴿ')
    text = text.replace('s', 'ˁ')
    text = text.replace('t', 'ᵀ')
    text = text.replace('u', 'ᵁ')
    text = text.replace('v', 'ᵛ')
    text = text.replace('w', 'ᵂ')
    text = text.replace('x', 'ˣ')
    text = text.replace('y', 'ʸ')
    text = text.replace('z', 'ᶻ')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-14)--------------------#
    text = ftext
    text = text.replace('a', 'Ａ')
    text = text.replace('b', 'Ｂ')
    text = text.replace('c', 'Ｃ')
    text = text.replace('d', 'Ｄ')
    text = text.replace('e', 'Ｅ')
    text = text.replace('f', 'Ｆ')
    text = text.replace('g', 'Ｇ')
    text = text.replace('h', 'Ｈ')
    text = text.replace('i', 'Ｉ')
    text = text.replace('j', 'Ｊ')
    text = text.replace('k', 'Ｋ')
    text = text.replace('l', 'Ｌ')
    text = text.replace('m', 'Ｍ')
    text = text.replace('n', 'Ｎ')
    text = text.replace('o', 'Ｏ')
    text = text.replace('p', 'Ｐ')
    text = text.replace('q', 'Ｑ')
    text = text.replace('r', 'Ｒ')
    text = text.replace('s', 'Ｓ')
    text = text.replace('t', 'Ｔ')
    text = text.replace('u', 'Ｕ')
    text = text.replace('v', 'Ｖ')
    text = text.replace('w', 'Ｗ')
    text = text.replace('x', 'Ｘ')
    text = text.replace('y', 'Ｙ')
    text = text.replace('z', 'Ｚ')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-15)--------------------#
    text = ftext
    text = text.replace('a', 'λ')
    text = text.replace('b', 'ß')
    text = text.replace('c', 'Ȼ')
    text = text.replace('d', 'ɖ')
    text = text.replace('e', 'ε')
    text = text.replace('f', 'ʃ')
    text = text.replace('g', 'Ģ')
    text = text.replace('h', 'ħ')
    text = text.replace('i', 'ί')
    text = text.replace('j', 'ĵ')
    text = text.replace('k', 'κ')
    text = text.replace('l', 'ι')
    text = text.replace('m', 'ɱ')
    text = text.replace('n', 'ɴ')
    text = text.replace('o', 'Θ')
    text = text.replace('p', 'ρ')
    text = text.replace('q', 'ƣ')
    text = text.replace('r', 'ર')
    text = text.replace('s', 'Ș')
    text = text.replace('t', 'τ')
    text = text.replace('u', 'Ʋ')
    text = text.replace('v', 'ν')
    text = text.replace('w', 'ώ')
    text = text.replace('x', 'Χ')
    text = text.replace('y', 'ϓ')
    text = text.replace('z', 'Հ')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-16)--------------------#
    text = ftext
    text = text.replace('A', '🅐')
    text = text.replace('a', '🅐')
    text = text.replace('b', '🅑')
    text = text.replace('c', '🅒')
    text = text.replace('d', '🅓')
    text = text.replace('e', '🅔')
    text = text.replace('f', '🅕')
    text = text.replace('g', '🅖')
    text = text.replace('h', '🅗')
    text = text.replace('i', '🅘')
    text = text.replace('j', '🅙')
    text = text.replace('k', '🅚')
    text = text.replace('l', '🅛')
    text = text.replace('M', '🅜')
    text = text.replace('m', '🅜')
    text = text.replace('n', '🅝')
    text = text.replace('o', '🅞')
    text = text.replace('p', '🅟')
    text = text.replace('q', '🅠')
    text = text.replace('r', '🅡')
    text = text.replace('s', '🅢')
    text = text.replace('t', '🅣')
    text = text.replace('u', '🅤')
    text = text.replace('v', '🅥')
    text = text.replace('w', '🅦')
    text = text.replace('x', '🅧')
    text = text.replace('y', '🅨')
    text = text.replace('z', '🅩')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-17)--------------------#
    text = ftext
    text = text.replace('a', '۰۪۫A۪۫۰')
    text = text.replace('b', '۰۪۫B۪۫۰')
    text = text.replace('c', '۰۪۫C۪۫۰')
    text = text.replace('d', '۰۪۫D۪۫۰')
    text = text.replace('e', '۰۪۫E۪۫۰')
    text = text.replace('f', '۰۪۫F۪۫۰')
    text = text.replace('g', '۰۪۫G۪۫۰')
    text = text.replace('h', '۰۪۫H۪۫۰')
    text = text.replace('i', '۰۪۫I۪۫۰')
    text = text.replace('j', '۰۪۫J۪۫۰')
    text = text.replace('k', '۰۪۫K۪۫۰')
    text = text.replace('l', '۰۪۫L۪۫۰')
    text = text.replace('m', '۰۪۫M۪۫۰')
    text = text.replace('n', '۰۪۫N۪۫۰')
    text = text.replace('o', '۰۪۫O۪۫۰')
    text = text.replace('p', '۰۪۫P۪۫۰')
    text = text.replace('q', '۰۪۫Q۪۫۰')
    text = text.replace('r', '۰۪۫R۪۫۰')
    text = text.replace('s', '۰۪۫S۪۫۰')
    text = text.replace('t', '۰۪۫T۪۫۰')
    text = text.replace('u', '۰۪۫U۪۫۰')
    text = text.replace('v', '۰۪۫V۪۫۰')
    text = text.replace('w', '۰۪۫W۪۫۰')
    text = text.replace('x', '۰۪۫X۪۫۰')
    text = text.replace('y', '۰۪۫Y۪۫۰')
    text = text.replace('z', '۰۪۫Z۪۫۰')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-18)--------------------#
    text = ftext
    text = text.replace('a', '̅α')
    text = text.replace('b', '̅в')
    text = text.replace('c', '̅c')
    text = text.replace('d', '̅ɒ')
    text = text.replace('e', '̅є')
    text = text.replace('f', '̅f')
    text = text.replace('g', '̅ɢ')
    text = text.replace('h', '̅н')
    text = text.replace('i', '̅ɪ')
    text = text.replace('j', '̅ᴊ')
    text = text.replace('k', '̅ĸ')
    text = text.replace('l', '̅ℓ')
    text = text.replace('m', '̅м')
    text = text.replace('n', '̅и')
    text = text.replace('o', '̅σ')
    text = text.replace('p', '̅ρ')
    text = text.replace('q', '̅q')
    text = text.replace('r', '̅я')
    text = text.replace('s', '̅s')
    text = text.replace('t', '̅τ')
    text = text.replace('u', '̅υ')
    text = text.replace('v', '̅v')
    text = text.replace('w', '̅ω')
    text = text.replace('x', '̅x')
    text = text.replace('y', '̅y')
    text = text.replace('z', '̅z')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-19)--------------------#
    text = ftext
    text = text.replace('A', '🄰')
    text = text.replace('a', '🄰')
    text = text.replace('b', '🄱')
    text = text.replace('c', '🄲')
    text = text.replace('d', '🄳')
    text = text.replace('e', '🄴')
    text = text.replace('f', '🄵')
    text = text.replace('g', '🄶')
    text = text.replace('h', '🄷')
    text = text.replace('i', '🄸')
    text = text.replace('j', '🄹')
    text = text.replace('k', '🄺')
    text = text.replace('l', '🄻')
    text = text.replace('M', '🄼')
    text = text.replace('m', '🄼')
    text = text.replace('n', '🄽')
    text = text.replace('o', '🄾')
    text = text.replace('p', '🄿')
    text = text.replace('q', '🅀')
    text = text.replace('r', '🅁')
    text = text.replace('s', '🅂')
    text = text.replace('t', '🅃')
    text = text.replace('u', '🅄')
    text = text.replace('v', '🅅')
    text = text.replace('w', '🅆')
    text = text.replace('x', '🅇')
    text = text.replace('y', '🅈')
    text = text.replace('z', '🅉')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-20)--------------------#
    text = ftext
    text = text.replace('A', '🅰')
    text = text.replace('a', '🅰')
    text = text.replace('b', '🅱')
    text = text.replace('c', '🅲')
    text = text.replace('d', '🅳')
    text = text.replace('e', '🅴')
    text = text.replace('f', '🅵')
    text = text.replace('g', '🅶')
    text = text.replace('h', '🅷')
    text = text.replace('i', '🅸')
    text = text.replace('j', '🅹')
    text = text.replace('k', '🅺')
    text = text.replace('l', '🅻')
    text = text.replace('m', '🅼')
    text = text.replace('M', '🅼')
    text = text.replace('n', '🅽')
    text = text.replace('o', '🅾')
    text = text.replace('p', '🅿')
    text = text.replace('q', '🆀')
    text = text.replace('r', '🆁')
    text = text.replace('s', '🆂')
    text = text.replace('t', '🆃')
    text = text.replace('u', '🆄')
    text = text.replace('v', '🆅')
    text = text.replace('w', '🆆')
    text = text.replace('x', '🆇')
    text = text.replace('y', '🆈')
    text = text.replace('z', '🆉')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-21)--------------------#
    text = ftext
    text = text.replace('a', 'a̷')
    text = text.replace('b', 'b̷')
    text = text.replace('c', 'c̷')
    text = text.replace('d', 'd̷')
    text = text.replace('e', 'e̷')
    text = text.replace('f', 'f̷')
    text = text.replace('g', 'g̷')
    text = text.replace('h', 'h̷')
    text = text.replace('i', 'i̷')
    text = text.replace('j', 'j̷')
    text = text.replace('k', 'k̷')
    text = text.replace('l', 'l̷')
    text = text.replace('m', 'm̷')
    text = text.replace('n', 'n̷')
    text = text.replace('o', 'o̷')
    text = text.replace('p', 'p̷')
    text = text.replace('q', 'q̷')
    text = text.replace('r', 'r̷')
    text = text.replace('s', 's̷')
    text = text.replace('t', 't̷')
    text = text.replace('u', 'u̷')
    text = text.replace('v', 'v̷')
    text = text.replace('w', 'w̷')
    text = text.replace('x', 'x̷')
    text = text.replace('y', 'y̷')
    text = text.replace('z', 'z̷')
    result.append(text +' '+ random.choice(item))
    #-----------------(#UzbProMax-22)--------------------#
    text = ftext
    text = text.replace('a', 'ᴀ')
    text = text.replace('b', 'ʙ')
    text = text.replace('c', 'ᴄ')
    text = text.replace('d', 'ᴅ')
    text = text.replace('e', 'ᴇ')
    text = text.replace('f', 'ᴈ')
    text = text.replace('g', 'ɢ')
    text = text.replace('h', 'ʜ')
    text = text.replace('i', 'ɪ')
    text = text.replace('j', 'ᴊ')
    text = text.replace('k', 'ᴋ')
    text = text.replace('l', 'ʟ')
    text = text.replace('m', 'ᴍ')
    text = text.replace('n', 'ɴ')
    text = text.replace('o', 'ᴏ')
    text = text.replace('p', 'ᴘ')
    text = text.replace('q', 'ᴓ')
    text = text.replace('r', 'ʀ')
    text = text.replace('s', 'ᴤ')
    text = text.replace('t', 'ᴛ')
    text = text.replace('u', 'ᴜ')
    text = text.replace('v', 'ᴠ')
    text = text.replace('w', 'ᴡ')
    text = text.replace('x', 'ᴥ')
    text = text.replace('y', 'ʏ')
    text = text.replace('z', 'ᴢ')

    result.append(text +' '+ random.choice(item))

    return result
